# Site settings
title: "Sgoly"
author: "githubnull"
description: "This is a web to broadcast our game: sgoly."
keywords: "game"
biography: "SiKun <a href="https://github.com/interfacekun"><img src="sikun_logo.png" width="16", height="16"></a> && GreenLittle <a href="https://github.com/GreenLittle"><img src="lvyuc.png" width="16", height="16"></a> &&githubnull <a href="https://github.com/GitHubNull"><img src="githubnull_logo.jpg" width="16", height="16"></a> && lvyan"
colophon: "© llsw.lkgame.com <br> @2017"
baseurl: "https://llsw.github.io/"
url: "https://llsw.github.io/"

twitter_username: null
github_username: llsw
linkedin_username: null
facebook_username: null
google-analytics: UA-69060-5

simple_search: http://baidu.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
