# Site settings
title: "Sgoly Is Coming"
author: "githubnull"
description: "This is a web to broadcast our game: sgoly."
keywords: "game"
biography: "I am a Professor of Software Engineering at the <a href='http://www.fe.up.pt'>Faculty of Engineering</a>, University of Porto and Senior Researcher at <a href='https://www.inesctec.pt'>INESC TEC</a>. Here you can find my <a href='/assets/thesis.pdf'>PhD Thesis</a> and my <a href='/assets/cv.pdf'>Résumé</a>."
colophon: "© llsw.lkgame.com <br> @2017"

baseurl: "llsw.github.io/blog"
url: "llsw.github.io"

twitter_username: null
github_username: llsw
linkedin_username: null
facebook_username: null
google-analytics: UA-69060-5

simple_search: http://baidu.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
