# Site settings
title: "Sgoly Is Coming"
author: "githubnull"
description: "This is a web to broadcast our game: sgoly."
keywords: "game"
biography: "We are game make teen."
colophon: "Test"

baseurl: "llsw.github.io"
url: "llsw.github.io"

twitter_username: null
github_username: llsw
linkedin_username: null
facebook_username: null
google-analytics: UA-69060-5

simple_search: http://baidu.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
