# Site settings
title: "Sgoly"
author: "githubnull"
description: "This is a web to broadcast our game: sgoly."
keywords: "game"
biography: null
colophon: "© llsw.lkgame.com <br> 2017"
baseurl: "https://llsw.github.io"
url: "https://llsw.github.io"

twitter_username: null
github_username: llsw
linkedin_username: null
facebook_username: null
google-analytics: UA-69060-5

simple_search: http://baidu.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
favicon: favicon.ico